// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type GetJsVersionTableResp struct {
	BaseResponse
	Result []JsVersionTable `json:"result"`
}

type JsVersionTable struct {
	Version string `json:"version"`
	Branch  string `json:"branch"`
	Note    string `json:"note"`
	RN      int64  `json:"rn"`
	Id      int64  `json:"id"`
}

type TestUserReqOne struct {
	UserId     int    `form:"userId,optional"`
	UserName   string `form:"userName,optional"`
	UserGender bool   `form:"userGender,optional"`
}
