// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tUsersFieldNames          = builder.RawFieldNames(&TUsers{})
	tUsersRows                = strings.Join(tUsersFieldNames, ",")
	tUsersRowsExpectAutoSet   = strings.Join(stringx.Remove(tUsersFieldNames, "`id`"), ",")
	tUsersRowsWithPlaceHolder = strings.Join(stringx.Remove(tUsersFieldNames, "`id`"), "=?,") + "=?"
)

type (
	tUsersModel interface {
		Insert(ctx context.Context, data *TUsers) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TUsers, error)
		Update(ctx context.Context, data *TUsers) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TUsers struct {
		Id       int64          `db:"id"`
		Name     string         `db:"name"`
		Age      int64          `db:"age"`
		Gender   sql.NullString `db:"gender"`
		CreateAt sql.NullTime   `db:"create_at"`
		UpdateAt sql.NullTime   `db:"update_at"`
		Num      sql.NullInt64  `db:"num"`
		Data     sql.NullString `db:"data"`
	}
)

func newTUsersModel(conn sqlx.SqlConn) *defaultTUsersModel {
	return &defaultTUsersModel{
		conn:  conn,
		table: "`t_users`",
	}
}

func (m *defaultTUsersModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTUsersModel) FindOne(ctx context.Context, id int64) (*TUsers, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tUsersRows, m.table)
	var resp TUsers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUsersModel) Insert(ctx context.Context, data *TUsers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, tUsersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Age, data.Gender, data.CreateAt, data.UpdateAt, data.Num, data.Data)
	return ret, err
}

func (m *defaultTUsersModel) Update(ctx context.Context, data *TUsers) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tUsersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Age, data.Gender, data.CreateAt, data.UpdateAt, data.Num, data.Data, data.Id)
	return err
}

func (m *defaultTUsersModel) tableName() string {
	return m.table
}
