// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	users "wfw_user/internal/handler/users"
	"wfw_user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/about_get_form_user",
				Handler: users.AboutGetTestFormReqHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/about_get_json_user",
				Handler: users.AboutGetTestJsonReqHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/about_post_form_user",
				Handler: users.AboutPostTestFormReqHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/about_post_json_user",
				Handler: users.AboutPostTestJsonReqHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get_test_user_one",
				Handler: users.GetTestUserOneHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/js_version",
				Handler: users.GetJsVersionTableHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post_test_user_one",
				Handler: users.PostTestUserTwoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/users"),
	)
}
